### ISSUE TITLE
Verify the token ?

### ISSUE THREAD

**Issue by dailycommit** [AurityLab/vue-recaptcha-v3#2]
This is really nice but how do I verify the token? Did you forget the main point in the example 😅 ?

**Comment by WipeAir** [comment]
Hi, actually not. This is just a library for the browser.
To verify the token (provided by the `$recaptcha(...)` function) look into the [official documentation from Google](https://developers.google.com/recaptcha/docs/v3#site-verify-response).
The concept behind recaptcha is that you request a token on the client and send it to your backend where you can verify it. And this library just covers the request on the client.

**Comment by dailycommit** [comment]
Thanks so much for your quick reply. I'm asking to clarify this issue;

Do I have to post this token to my own back-end or google verify (https://www.google.com/recaptcha/api/siteverify)

see: https://developers.google.com/recaptcha/docs/verify

Thank you.

**Comment by WipeAir** [comment]
The workflow would be the following:
* Request the token on the client with this library
* Send the token to **your** backend (Not from the client directly to Google, because it would expose your secret key)
* Post the token to Google from **your** backend
* Take proper actions according to the returned score from Google on your backend.

And do not forget, that reCAPTCHA v3 differs from the previous versions! The v3 is based on a *score* system and does not require the user to solve any type of captcha, rather you're in carge of taking proper actions, like requesting TFA, etc.

**Comment by WipeAir** [comment]
No problem :)

**Comment by vesper8** [comment]
geez.. couldn't the recaptcha return the score directly to the front-end instead? why is this extra loop (client -> server -> google -> server -> analyze scrore -> client) necessary ? can't the client make a decision based on the score right away?

**Comment by WipeAir** [comment]
I actually hat the same thought at the beginning, but it makes kinda sense to do it like this.
Because if you process the score directly on the front-end there is always a chance for manipulation.
Anyway, you can avoid this loop by executing the request with your secret key on the client, but that's no good idea at all and I wouldn't recommend it.

**Comment by vesper8** [comment]
thanks.. I've implemented it with the long loop now and my server doing the verification, I just don't want this to makes my form submissions get much longer.. but we'll see how much it impacts it

**Comment by bigoper** [comment]
@vesper8 
I know you "hate" the ~long loop due to "long form submission", but!!!
You can do the followings:
1. back-end 'acknowledge' the 'post' request (response 200)
* the client should not wait for the email to be sent...
2. the back-end should create a task to send an email (based on the 'post' provided info)
- if 'sent ok' -> perfect!
- if 'not sent' -> report the issue to 'admin'
3. the idea is to 'just' handle the 'send email request'

I hope it was helpful.

**Comment by vesper8** [comment]
sorry @bigoper you're losing me now when talking about email.. what email? Why should an admin receive an email if someone fails the recaptcha?
