### ISSUE TITLE
Recaptcha doesn't catch spam

### ISSUE THREAD

**Issue by kondrashkin465** [AurityLab/vue-recaptcha-v3#387]
Hi. I installed recaptcha v3 into my login form - but i think recaprtcha doesn't catch spam. I send a lot of requests but recaptcha doesn't show me modal with images(gidranst or bus and ect.) for check on robot . It's normal behavior?
Because recaptcha v2 shows modal with images after 5-7 attempts

**Comment by WipeAir** [comment]
Hey,
that's because reCAPTCHA v3 works differently than v2.
Instead of showing a "challenge" to the user, you'll get a so-called "score" as a response to the action. The score indicates how trustworthy the user is. E.g. if the score is below a certain threshold you may force the user to verify a 2FA.
You can read more about it here: https://developers.google.com/recaptcha/docs/v3
